### @summary HEALTH CHECK
### @route   GET /health/check
### @access  Public
### @header  null 
### @body    null
### @returns json 
### {
###   "status": "200",
###   "endpoint": "localhost:1337/health/check",
###		"message": "message": "server successfully running on localhost:1337."
### }
GET http://localhost:1337/health/check

###

GET https://quiz-questions-api.herokuapp.com/health/check