# @summary GET ALL QUESTIONS
# @route   GET /api/quiz/questions/get-all-questions
# @access  Public
# @header  null 
# @body    null
# @returns json 
# {
#   route: string,
#   error: boolean,
#   count: int
#   questions: [
#     _id: string,
#     question: string,
#     answers: [string, string, ...]
#   ]
# }
GET http://localhost:1337/api/quiz/questions/get-all-questions